"""Redis-backed response cache for read-heavy GET endpoints.

Introduced to reduce PostgreSQL load / improve API latency for the
Customer 360 API. Design goals:

- **Fail open**: any Redis connectivity problem (down, timeout, wrong
  password) silently falls back to hitting the database directly. Caching is
  a performance optimization here, never a hard dependency.
- **Generic**: ``cache_response`` is a decorator that can wrap ANY FastAPI GET
  route (hand-written or generated by ``core/routers/_generic.py``) without
  that route needing to know anything about Redis. It works by JSON-encoding
  whatever the route returns (via ``fastapi.encoders.jsonable_encoder``,
  which happily handles ORM objects, Pydantic models, dicts, lists, UUIDs,
  datetimes, Decimals, etc.) and replaying that same JSON-safe structure on a
  cache hit -- FastAPI's ``response_model`` validates/serializes a plain
  dict/list identically to an ORM object, so callers can't tell the
  difference.
- **Prefix-scoped invalidation**: write endpoints call
  ``invalidate_prefix(<entity prefix>)`` after a successful create/update/
  delete, which SCAN+DELETEs every cache key stored under that prefix.

CAVEAT: customer360-backend/identity_resolution (the CIR worker) writes to
``cdp_raw_profiles_stage`` / ``cdp_master_profiles`` / etc. directly via
psycopg2, bypassing this API entirely -- those writes do NOT trigger cache
invalidation here. Staleness from that path is bounded by ``CACHE_TTL_SECONDS``
(default 60s), which is an acceptable tradeoff for a performance cache rather
than a source of truth.
"""

import functools
import hashlib
import inspect
import json
import logging
import uuid
from datetime import date, datetime
from typing import Any, Callable, Optional

import redis
from fastapi.encoders import jsonable_encoder
from starlette.requests import Request

from leo_customer360_dao.cache import get_redis_client
from leo_customer360_dao.config import settings

logger = logging.getLogger(__name__)

# Only these simple, JSON-friendly kwarg types are folded into the cache key.
# This is also what lets the decorator transparently skip the injected
# SQLAlchemy `Session` (and any other non-primitive dependency) without the
# caller having to name it explicitly.
_CACHEABLE_PARAM_TYPES = (
    str,
    int,
    float,
    bool,
    uuid.UUID,
    date,
    datetime,
    type(None),
)


def _build_cache_key(prefix: str, params: dict[str, Any]) -> str:
    normalized = json.dumps(params, sort_keys=True, default=str)
    digest = hashlib.sha256(normalized.encode("utf-8")).hexdigest()[:16]
    return f"cache:{prefix}:{digest}"


def cache_get(key: str) -> Optional[Any]:
    client = get_redis_client()
    if client is None:
        return None
    try:
        raw = client.get(key)
    except redis.RedisError:
        logger.warning("Redis GET failed for key=%s; falling back to DB.", key, exc_info=True)
        return None
    if raw is None:
        return None
    try:
        return json.loads(raw)
    except (TypeError, json.JSONDecodeError):
        logger.warning("Redis cache entry was invalid JSON for key=%s; ignoring it.", key)
        return None


def cache_set(key: str, value: Any, ttl: Optional[int] = None) -> None:
    client = get_redis_client()
    if client is None:
        return
    try:
        client.set(key, json.dumps(value, default=str), ex=ttl or settings.cache_ttl_seconds)
    except (redis.RedisError, TypeError, ValueError):
        logger.warning("Redis SET failed for key=%s.", key, exc_info=True)


def invalidate_prefix(prefix: str) -> None:
    """Deletes every cache entry previously written under ``cache_response(prefix)``
    (or any prefix starting with it, e.g. ``"<prefix>/list"``/``"<prefix>/item"``)."""
    client = get_redis_client()
    if client is None:
        return
    try:
        pattern = f"cache:{prefix}*"
        cursor = 0
        while True:
            cursor, keys = client.scan(cursor=cursor, match=pattern, count=200)
            if keys:
                client.delete(*keys)
            if cursor == 0:
                break
    except redis.RedisError:
        logger.warning("Redis SCAN/DELETE failed for prefix=%s.", prefix, exc_info=True)


def cache_response(prefix: str, ttl: Optional[int] = None) -> Callable:
    """Decorator: caches a GET route's JSON-encoded result in Redis.

    Must be applied UNDER the router decorator (i.e. listed after
    ``@router.get(...)`` in source order) so FastAPI registers the caching
    wrapper as the actual endpoint:

        @router.get("/", response_model=list[ReadSchema])
        @cache_response("things/list")
        def list_things(...): ...
    """

    def decorator(func: Callable) -> Callable:
        @functools.wraps(func)
        def wrapper(*args: Any, **kwargs: Any) -> Any:
            bound = inspect.signature(func).bind_partial(*args, **kwargs)
            cache_params = {
                name: value
                for name, value in bound.arguments.items()
                if isinstance(value, _CACHEABLE_PARAM_TYPES)
            }
            request = next(
                (value for value in (*args, *kwargs.values()) if isinstance(value, Request)),
                None,
            )
            request_tenant_id = getattr(getattr(request, "state", None), "tenant_id", None)
            if request_tenant_id:
                cache_params["_tenant_id"] = str(request_tenant_id)
            key = _build_cache_key(prefix, cache_params)

            cached_value = cache_get(key)
            if cached_value is not None:
                return cached_value

            result = func(*args, **kwargs)
            cache_set(key, jsonable_encoder(result), ttl)
            return result

        return wrapper

    return decorator
