"""Import every ORM model so Base.metadata is fully populated (needed for
relationship/FK resolution and any metadata-driven tooling)."""

from core.models.base import Base
from core.models.content import CdpContentItem
from core.models.crm import (
    Account,
    Campaign,
    CampaignContentItem,
    CampaignDispatchLog,
    CampaignMember,
    Contact,
    EmailProviderConfig,
    EmailTemplate,
    Industry,
    Lead,
    LeadSource,
    Opportunity,
    SegmentSyncRun,
)
from core.models.graph import GraphEdge
from core.models.identity import (
    CdpCustomerPersona,
    CdpDomainProfile,
    CdpIdentityIndex,
    CdpIdResolutionStatus,
    CdpMasterProfile,
    CdpPersonaFeature,
    CdpPersonaHistory,
    CdpPersonaScoreDetail,
    CdpProfileAttribute,
    CdpProfileLink,
    CdpProfileMergeHistory,
    CdpRawProfileStage,
    CdpScoringModel,
)
from core.models.relations import CdpRelation, CustomerContact, RelationType, Transaction
from core.models.segmentation import CdpSegment
from core.models.system import (
    SysDataSource,
    SysDomain,
    SysTenantDomain,
    SysUser,
    SysUserInfo,
    sys_organization_table,
    sys_tenant_table,
)

__all__ = [
    "Base",
    "Account",
    "Campaign",
    "CampaignContentItem",
    "CampaignDispatchLog",
    "CampaignMember",
    "CdpContentItem",
    "Contact",
    "EmailProviderConfig",
    "EmailTemplate",
    "Industry",
    "Lead",
    "LeadSource",
    "Opportunity",
    "SegmentSyncRun",
    "GraphEdge",
    "CdpCustomerPersona",
    "CdpDomainProfile",
    "CdpIdentityIndex",
    "CdpIdResolutionStatus",
    "CdpMasterProfile",
    "CdpPersonaFeature",
    "CdpPersonaHistory",
    "CdpPersonaScoreDetail",
    "CdpProfileAttribute",
    "CdpProfileLink",
    "CdpProfileMergeHistory",
    "CdpRawProfileStage",
    "CdpRelation",
    "CdpScoringModel",
    "CdpSegment",
    "CustomerContact",
    "Transaction",
    "RelationType",
    "SysDataSource",
    "SysDomain",
    "SysTenantDomain",
    "SysUser",
    "SysUserInfo",
    "sys_organization_table",
    "sys_tenant_table",
]
