#!/usr/bin/env bash
# Mint a least-privilege kubeconfig for CI to deploy customer360-event-api.
#   ./make-kubeconfig.sh [output-path]
#
# Run this ONCE, with an ADMIN kubeconfig (the one downloaded from the VKS console).
# It applies ./rbac.yaml and writes a kubeconfig authenticating as the
# `event-api-deployer` ServiceAccount — an identity that can deploy this one service into
# this one namespace and nothing else. Put the result in the VKS_KUBECONFIG repo secret
# instead of the cluster-admin kubeconfig.
#
# The token it embeds does NOT expire: it comes from a `kubernetes.io/service-account-token`
# Secret, not from `kubectl create token`. A short-lived token would deploy once and then
# start failing CD, the same way a job-scoped registry token breaks later image pulls.
#
# Overrides:
#   KUBECONFIG           the ADMIN kubeconfig to run this with (required, as usual)
#   SA_NAME              ServiceAccount name (default event-api-deployer)
set -euo pipefail
cd "$(dirname "$0")"

NAMESPACE="${EVENT_API_NAMESPACE:-customer360}"
SA_NAME="${SA_NAME:-event-api-deployer}"
SECRET_NAME="${SA_NAME}-token"
OUT="${1:-../../kubeconfig-vks-ci.yaml}"   # gitignored by deployments/server/.gitignore

command -v kubectl >/dev/null 2>&1 || { echo "ERROR: kubectl not found on PATH."; exit 1; }
[[ -n "${KUBECONFIG:-}" ]] || echo ">> NOTE: KUBECONFIG is unset — using kubectl's default context."
kubectl version -o json >/dev/null 2>&1 || { echo "ERROR: cannot reach the cluster."; exit 1; }

CONTEXT="$(kubectl config current-context)"
SERVER="$(kubectl config view --minify --raw -o jsonpath='{.clusters[0].cluster.server}')"
[[ -n "$SERVER" ]] || { echo "ERROR: could not read the API server URL from the current context."; exit 1; }
echo ">> Cluster: $CONTEXT ($SERVER)"
echo ">> Granting '$SA_NAME' deploy rights in namespace '$NAMESPACE' ..."

# The RBAC objects are namespaced, so the namespace has to exist before they can be
# created. This normally runs BEFORE the first deploy, so do not assume it is there.
kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f - >/dev/null

kubectl apply -f rbac.yaml

# The token controller populates the Secret asynchronously — usually instantly, but poll
# rather than race it, because an empty token would produce a silently unusable kubeconfig.
echo ">> Waiting for the ServiceAccount token ..."
TOKEN=""
for _ in $(seq 1 30); do
  TOKEN="$(kubectl -n "$NAMESPACE" get secret "$SECRET_NAME" -o jsonpath='{.data.token}' 2>/dev/null || true)"
  [[ -n "$TOKEN" ]] && break
  sleep 1
done
[[ -n "$TOKEN" ]] || {
  echo "ERROR: the token Secret '$SECRET_NAME' was never populated."
  echo "       Some hardened clusters disable the token controller; in that case use"
  echo "       'kubectl -n $NAMESPACE create token $SA_NAME --duration=8760h' and paste"
  echo "       that token in below — but check the API server allows that lifetime."
  exit 1
}
TOKEN="$(printf '%s' "$TOKEN" | base64 -d)"
CA="$(kubectl -n "$NAMESPACE" get secret "$SECRET_NAME" -o jsonpath='{.data.ca\.crt}')"
[[ -n "$CA" ]] || { echo "ERROR: the token Secret has no ca.crt."; exit 1; }

umask 077
cat > "$OUT" <<KUBECONFIG
# GENERATED by customer360-event-api/ci-access/make-kubeconfig.sh — do not edit.
# Authenticates as ServiceAccount $NAMESPACE/$SA_NAME (least privilege; see rbac.yaml).
apiVersion: v1
kind: Config
current-context: event-api-ci
clusters:
  - name: vks
    cluster:
      server: $SERVER
      certificate-authority-data: $CA
users:
  - name: $SA_NAME
    user:
      token: $TOKEN
contexts:
  - name: event-api-ci
    context:
      cluster: vks
      user: $SA_NAME
      namespace: $NAMESPACE
KUBECONFIG
chmod 600 "$OUT"

# Prove it works, and prove it is actually limited — a kubeconfig that silently still has
# admin (or silently has nothing) is worse than no kubeconfig at all.
echo ">> Verifying the generated kubeconfig ..."
can() { KUBECONFIG="$OUT" kubectl auth can-i "$@" 2>/dev/null || true; }
printf '   create deployments in %-12s : %s\n' "$NAMESPACE" "$(can create deployments -n "$NAMESPACE")"
printf '   create scaledobjects in %-9s : %s\n' "$NAMESPACE" "$(can create scaledobjects.keda.sh -n "$NAMESPACE")"
# --subresource=exec, NOT the "pods/exec" slash form: `kubectl auth can-i` does not
# resolve a subresource written that way and answers "no" even when the Role grants it.
# The RBAC rule itself is still written as resources: [pods/exec] — only this query differs.
printf '   exec into pods in %-15s : %s\n' "$NAMESPACE" "$(can create pods --subresource=exec -n "$NAMESPACE")"
printf '   %-34s : %s (expected: no)\n' "delete the namespace" "$(can delete namespaces)"
printf '   %-34s : %s (expected: no)\n' "read secrets in kube-system" "$(can get secrets -n kube-system)"
printf '   %-34s : %s (expected: no)\n' "list nodes" "$(can list nodes)"

echo
echo ">> Wrote $OUT"
echo "   Use it locally:   KUBECONFIG=$OUT ../../deploy-event-api.sh <uat|prod>"
echo "   Store it for CD:  gh secret set VKS_KUBECONFIG < $OUT"
echo "   It contains a non-expiring token — treat it as a credential and do not commit it."
