# UAT overlay — Keycloak runs as a Docker container on the SAME VM as the API.
# Read by deploy-sso.sh (grep); no Terraform is involved.

sso_server_key      = "api"                    # SHARE the customer360-api box (c360-api-uat-api, 10.100.1.5)
keycloak_image      = "keycloak/keycloak:26.7"
keycloak_command    = "start-dev"              # dev mode: HTTP + lenient hostname — fine for uat
keycloak_http_port  = 8080
keycloak_admin_user = "admin"
keycloak_hostname   = "http://103.245.254.29:8080" # public entry = the load balancer (deployments/load_balancer)
keycloak_db_name    = "db_keycloak"            # already created by postgres/init/02-create-keycloak-db.sql

# Cap the JVM heap: the shared 2 GB box ALSO runs customer360-api + Redis, so let
# Keycloak's default (up to 70% of RAM) run wild would OOM the box.
java_heap = "-Xms256m -Xmx512m"

# --- API wiring: how ../server/deploy-api.sh points customer360-api at Keycloak ---
# When api_sso_enabled=true the api is deployed with SSO_LOGIN=true (OIDC auth-code +
# introspection) instead of the dev local-JWT login. The client secret is generated by
# bootstrap-realm.py into .env (KEYCLOAK_CLIENT_SECRET). sso_login_url is the PUBLIC (LB)
# URL: it's used by BOTH the browser (authorize redirect) and the backend (introspection;
# the box can hairpin to the LB, verified).
api_sso_enabled        = true
api_sso_login_url      = "http://103.245.254.29:8080"
api_keycloak_realm     = "customer360"
api_keycloak_client_id = "customer360-api"

# Keycloak client redirect URI(s), tightened from "*" to the frontend's public origin.
# Must cover the SPA's redirect (window.location.origin + pathname); the trailing /*
# allows the app's paths. Comma-separate for multiple. Consumed by bootstrap-realm.py.
sso_redirect_uris = "http://103.245.254.29:8890/*"
